In [1]:
import numpy as np

In [2]:
myarray = np.array([10, 15, 20, 25, 30])

In [3]:
myarray

array([10, 15, 20, 25, 30])

In [4]:
# Now we can even give datatype to the elements that we have entered in the array explicitely

In [5]:
myarray = np.array([10, 15, 16, 17, 18], np.int16)

In [6]:
myarray

array([10, 15, 16, 17, 18], dtype=int16)

In [7]:
myarray = np.array([10, 15, 16, 17, 18], np.float16)

In [8]:
myarray

array([10., 15., 16., 17., 18.], dtype=float16)

In [9]:
myarray = np.array([10, 15, 16, 17, 18], np.double)

In [10]:
myarray

array([10., 15., 16., 17., 18.])

In [12]:
# Hence we can give data type to the elements in the array explicitely
# Keep in mind that we can give the bits to datatype after using number after data type

In [13]:
myarray[0]

10.0

In [14]:
myarray[3]

17.0

In [15]:
# we can craete and manipulate 2D array using numpy function

In [16]:
myarray = np.array([[10, 15, 16, 17], [20, 40, 50, 60], [100, 200, 300, 400]])

In [17]:
myarray[0]

array([10, 15, 16, 17])

In [18]:
myarray[0][3]

17

In [20]:
myarray[0, 3]

17

In [21]:
# This is how we can access different elements of the array (same as of the normal array in any language)

In [22]:
myarray.shape

(3, 4)

In [23]:
# .shape is used to get basic information about how many numbers of rows and columns are there in any of the array

In [24]:
myarray.dtype

dtype('int32')

In [25]:
# This is used to get the data type of elements present inside of numpy array

In [26]:
myarray[0, 3] = 100

In [27]:
myarray

array([[ 10,  15,  16, 100],
       [ 20,  40,  50,  60],
       [100, 200, 300, 400]])

In [28]:
myarray[0, 3]

100

In [29]:
# This is how we can update the elements inside of the numpy array

# Creation of numpy array using tuples and list

In [31]:
listarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
listarray.size

9

In [34]:
listarray.shape

(3, 3)

In [35]:
# This is how we can create python array using list 

In [36]:
myarray = np.array({10, 5, 0, 1})

In [37]:
myarray

array({0, 1, 10, 5}, dtype=object)

In [38]:
# numpy array can also be craeted using object too as shown above

# Instrinsic array creation

In [39]:
myarray = np.zeros(5)

In [40]:
myarray

array([0., 0., 0., 0., 0.])

In [41]:
myarray = np.zeros((3, 3))

In [42]:
myarray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
# This is how you initialize array with zeros in it

In [44]:
myarray = np.arange(10)

In [45]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
myarray = np.array([[np.arange(3)], [np.arange(3)]])

In [47]:
myarray

array([[[0, 1, 2]],

       [[0, 1, 2]]])

In [48]:
# arange function goes from 0 to n-1

In [51]:
lspace = np.linspace(1, 10, 3)

In [52]:
lspace

array([ 1. ,  5.5, 10. ])

In [54]:
# this np.linspace element will give me 3 numbers from 1 to 10 which will be equally spaced

In [55]:
emp = np.empty((3, 3))

In [56]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# this is emp function which is used to create empty array of given dimension 

In [58]:
emp_like = np.empty_like(lspace)

In [59]:
emp_like

array([ 1. ,  5.5, 10. ])

In [60]:
# empty like is a function which is used for the purpose of intializing the new array of size equal to size provided in params

In [61]:
identity = np.identity(3)

In [62]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# np.identity is a function which is used to have identity matrix of given dimension

In [64]:
one_d = np.arange(99)

In [65]:
one_d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
two_d = one_d.reshape(3, 33)

In [69]:
two_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [72]:
# name of the array .reshape is used for the purpose of reshaping the array in such a way that it will ve converted into 2 dimension
# one thing to note here is that we have to conider the size while reshaping otherwise it will give us error

In [73]:
# Now we have converted a one d array into a two d array
# to convert two d to one d we can use ravel function

In [76]:
one_d = two_d.ravel()

In [77]:
one_d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [85]:
matrix = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [86]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
# axis is used in most of the numpy function and hence we can use the number accordingly

In [88]:
sum_of_cols = matrix.sum(axis = 0)

In [89]:
sum_of_cols

array([12,  8,  9])

In [90]:
# hence axis 0 is used in the case where we have to calculate sum or any operation in column wise from top to down

In [91]:
# simillarly axis 1 will be used in case where we have to find the calculation in the form of rows from left to right

In [92]:
sum_of_rows = matrix.sum(axis = 1)

In [93]:
sum_of_rows

array([ 6, 15,  8])

In [94]:
# for axis = 0 the arraw is in the downward direction

In [95]:
# for axis = 1 the arrow is in the horizontal direction

In [96]:
matrix.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [97]:
# .T is used in the array where we have to find transpose of the given matrix

In [98]:
# to iterate through array without using two d logic we can use flat method

In [99]:
for item in matrix.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [100]:
matrix.ndim

2

In [101]:
# number of dimension in the given array is given by ndim

In [104]:
array = np.array([10,20,30,40,50,60])

In [105]:
maxIndex = array.argmax()

In [106]:
maxIndex

5

In [108]:
# argmax is a method which is used to find index of maximum elements in the array

In [109]:
array.argmin()

0

In [111]:
array = np.array([50, 20, 30, 40, 10, 100])

In [112]:
array.argsort()

array([4, 1, 2, 3, 0, 5], dtype=int64)

In [113]:
# argsort is a function which is used to find index of the elements in increasing order

In [114]:
matrix.argmin()

8

In [115]:
matrix.argmax()

6

In [116]:
matrix.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [118]:
# when we have argmin and then argmax to find max and min of the array then interpreter first straighten up the array and then
# find max and min element of the array but for argsort index are sorted in rowwise fashion

In [119]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [122]:
matrix.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [123]:
matrix.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [124]:
# keep in mind that these are indices only and not actual values

In [127]:
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [128]:
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
matrix + matrix2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [130]:
# we can perform sum of two matrices as per the index matched

In [131]:
matrix * matrix2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  8,  0]])

In [132]:
sqrtMatrix = np.sqrt(matrix)

In [133]:
sqrtMatrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [134]:
# sqrt is used to get square root of the matrix

In [136]:
# min max and sum can also be calculated using respective function and then using axis function

In [137]:
# where function is used to retriev indices of the array where we want them to give us answers in the way we wanted

In [138]:
np.where(matrix < 5)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [144]:
# it is returned in the form of tuple
# above output is based on the tuple as they are in the form of axis 0 and then axis 1

In [145]:
np.count_nonzero(matrix)

8

In [146]:
np.count_nonzero(matrix2)

9