In [27]:
import numpy as np

In [28]:
# numpy array can be created just like any other python list with given range values

In [29]:
l1 = np.arange(10000)

In [30]:
l1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [31]:
# Here array is created with element which has range of numbers in the range 0 to 9999

In [32]:
l1 = np.arange(1, 10001)

In [33]:
l1

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [34]:
# Now we have got to know that we have the numpy in the range of particular number
# How can we prove that it is good to use the numpy array as it is faster than anything

In [47]:
SIZE = 100000

In [54]:
l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()

result = [(x + y) for x, y in zip (l1, l2)]
print("Time for the python list is: ", (time.time() - start) * 1000)

start = time.time()
result = a1 + a2

print("Time for numpy array: ", (time.time() - start) * 1000)

Time for the python list is:  23.334741592407227
Time for numpy array:  9.371042251586914


In [55]:
# So look there's huge difference between working of the regular list and numpy array

In [56]:
# There are others features of the numpy array as well that we have to consider

In [57]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

In [58]:
a2 = np.array([1,2,3,4,5,6,7,8,9])

In [59]:
a1 + a2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
a1 * a2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
a1 / a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
a1** a2

array([        1,         4,        27,       256,      3125,     46656,
          823543,  16777216, 387420489])